"""
Mock property data for the API server.
Matches the shape of mockData.js on the frontend.
"""

MOCK_PROPERTIES = [
    {
        "id": "prop_001",
        "name": "Kensington Garden Flat",
        "address": "42 Kensington High St, London W8 4PT",
        "neighborhood": "Kensington and Chelsea",
        "propertyType": "Apartment",
        "roomType": "Entire home/apt",
        "bedrooms": 2,
        "bathrooms": 1,
        "accommodates": 4,
        "beds": 3,
        "currentPrice": 175,
        "minPrice": 120,
        "maxPrice": 350,
        "rating": 4.82,
        "reviewCount": 47,
        "status": "active",
        "occupancyRate": 78,
        "latitude": 51.4993,
        "longitude": -0.1928,
        "isSuperhost": True,
        "amenities": [
            "wifi", "kitchen", "heating", "washer", "dryer",
            "tv", "iron", "workspace", "smoke_alarm",
        ],
    },
    {
        "id": "prop_002",
        "name": "Shoreditch Loft Studio",
        "address": "18 Curtain Rd, London EC2A 3AT",
        "neighborhood": "Hackney",
        "propertyType": "Apartment",
        "roomType": "Entire home/apt",
        "bedrooms": 0,
        "bathrooms": 1,
        "accommodates": 2,
        "beds": 1,
        "currentPrice": 95,
        "minPrice": 65,
        "maxPrice": 200,
        "rating": 4.71,
        "reviewCount": 89,
        "status": "active",
        "occupancyRate": 84,
        "latitude": 51.5235,
        "longitude": -0.0794,
        "isSuperhost": True,
        "amenities": [
            "wifi", "kitchen", "heating", "washer", "tv",
            "air_conditioning", "workspace", "smoke_alarm",
        ],
    },
    {
        "id": "prop_003",
        "name": "Camden Victorian Townhouse",
        "address": "7 Gloucester Crescent, London NW1 7DL",
        "neighborhood": "Camden",
        "propertyType": "House",
        "roomType": "Entire home/apt",
        "bedrooms": 3,
        "bathrooms": 2,
        "accommodates": 6,
        "beds": 4,
        "currentPrice": 280,
        "minPrice": 180,
        "maxPrice": 500,
        "rating": 4.93,
        "reviewCount": 31,
        "status": "active",
        "occupancyRate": 65,
        "latitude": 51.5388,
        "longitude": -0.1462,
        "isSuperhost": True,
        "amenities": [
            "wifi", "kitchen", "heating", "washer", "dryer",
            "tv", "iron", "workspace", "free_parking", "smoke_alarm",
            "air_conditioning",
        ],
    },
]
